### ISSUE TITLE
Remap controls in Desktop OS?

### ISSUE THREAD

**Issue by ankushKun** [game-de-it/rg35xx#3]
I wanted to remap the controls to the following

DPad: mouse movement
A,B,X,Y : arrow keys
Start: enter
Select: escape
L1: right click
R1: left click
L2/R2: other possible keys (undecided)

But I couldn't find where to configure these.
Could you please share where the config file is located, assuming it is using something like QJoypad (couldn't find it's config in .config too)

Thanks

**Comment by game-de-it** [comment]
"gptokeyb" is used for mapping the gamepad and keyboard.
The configuration file is `/usr/local/share/gptokeyb/default.gptk`
You can confirm that gptokeyb is running with the `ps -efH` command.

# About the mechanism of DesktopOS
DesktopOS uses Anbernic's StockOS as is.
stockOS is based on ubuntu, and the internal mechanism of the OS follows ubuntu specifications.

Therefore, the `/etc/rc.local` file and `/.config/autostart/` directory are used as a mechanism to generate DesktopOS from stockOS.

The flow of starting the OS is to read and execute the `/etc/rc.local` file in addition to the processing of systemd.
Some comments are left so that you can understand what is going on.

At the end, when lightdm starts, the files in the `/.config/autostart/` directory are executed.
gptokeyb is executed here, and control with a gamepad becomes possible.

I hope this is helpful.

**Comment by ankushKun** [comment]
This is very useful information, thank you so much.

One last thing about keyboard input, onboard doesnot seem to run, and trying to run it through the terminal gives the following error:

```
root@ANBERNIC:/# onboard
Traceback (most recent call last):
  File "/usr/bin/onboard", line 32, in <module>
    from Onboard.Exceptions import chain_handler
  File "/usr/lib/python3/dist-packages/Onboard/__init__.py", line 23, in <module>
    from Onboard.utils import Translation
  File "/usr/lib/python3/dist-packages/Onboard/utils.py", line 933, in <module>
    import cairo
  File "/usr/lib/python3/dist-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: /usr/lib/arm-linux-gnueabihf/libcairo.so.2: undefined symbol: FT_Get_Var_Design_Coordinates

root@ANBERNIC:/# onboard-settings
Traceback (most recent call last):
  File "/usr/bin/onboard-settings", line 21, in <module>
    from Onboard.settings import Settings
  File "/usr/lib/python3/dist-packages/Onboard/__init__.py", line 23, in <module>
    from Onboard.utils import Translation
  File "/usr/lib/python3/dist-packages/Onboard/utils.py", line 933, in <module>
    import cairo
  File "/usr/lib/python3/dist-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: /usr/lib/arm-linux-gnueabihf/libcairo.so.2: undefined symbol: FT_Get_Var_Design_Coordinates
```

**Comment by ankushKun** [comment]
Also, do you know what keybind is for the menu button and L2, R2?
There seems to be a mismatch in configs, when I define `l1 = esc` and `l2 = enter` it gets mapped to select and start on RG35XXSP. and `back = mouse_left` and `start` = mouse_right` gets mapped to L1 and R1 haha.
And nothing seems to work for L2 and R2

**Comment by game-de-it** [comment]
I'm busy creating another CFW, so sorry for the late reply.

Regarding "onboard", the cause may be that the referenced library is old or new.
You may want to build it from the onboard source code using the DesktopOS build environment.

For "gptokeyb", you may need to add a unique keymap for RG35xxSP, so you may need to download the source code and modify the contents.
You should be able to check the keymap using the `evtest` command etc.
